// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/feed"
    | "/later"
    | "/paper-trail"
    | "/people"
    | "/screener"
    | "/set-aside"
    | "/settings/accounts"
    | "/today"
  }
}

export {};
