// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/board"
    | "/calendar"
    | "/notes"
    | "/people"
    | "/reading"
    | "/receipts"
    | "/screener"
    | "/settings"
    | "/settings/accounts"
    | "/settings/appearance"
    | "/settings/mail"
    | "/settings/security"
    | "/snoozed"
    | "/today"
  }
}

export {};
