// Auto-generated by Neutron. Do not edit.
declare module "@neutron-build/core" {
  interface NeutronGeneratedRouteMap {
    paths:
    | "/"
    | "/people"
    | "/reading"
    | "/receipts"
    | "/screener"
    | "/settings/accounts"
    | "/snoozed"
    | "/today"
  }
}

export {};
